<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Course;
use Symfony\Component\Intl\Intl;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFiltersData()
    {
        $filtersData = [];

        $queryBuilder = $this->createQueryBuilder('entity');

        $result = $queryBuilder
            ->where($queryBuilder->expr()->eq('entity.status', $queryBuilder->expr()->literal('publish')))
            ->getQuery()->getResult();

        /**
         * @var Course $item
         */
        foreach ($result as $item) {
            $filtersData['categories'][$item->getCategory()->getId()] = $item->getCategory();
            $filtersData['users'][$item->getUser()->getId()] = $item->getUser();
            $filtersData['languages'][$item->getLanguage()] =  Intl::getLanguageBundle()->getLanguageName($item->getLanguage());
        }

        return $filtersData;
    }
}
