<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Course;
use AppBundle\Entity\User;

/**
 * CourseNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseNotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function viewAllNotifications(Course $course, User $user)
    {
        $qb = $this->createQueryBuilder('entity');

        $qb->update('AppBundle:CourseNotification', 'entity')
            ->set('entity.viewed', 1)
            ->where($qb->expr()->eq('entity.course', $course->getId()))
            ->andWhere($qb->expr()->eq('entity.user', $user->getId()))
            ->getQuery()->execute();
    }
}
