<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Course;
use Symfony\Component\Intl\Intl;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{

    public function createQuery($criteria, $order)
    {
        $queryBuilder = $this->createQueryBuilder('entity');

        foreach ($criteria as $key => $value) {
            $queryBuilder->andWhere($queryBuilder->expr()->eq('entity.'.$key, $queryBuilder->expr()->literal($value)));
        }

        foreach ($order as $key => $value) {
            $queryBuilder->addOrderBy('entity.'.$key, $value);
        }

        return $queryBuilder->getQuery();
    }

    public function getFiltersData()
    {
        $filtersData = ['categories' => [], 'users' => [], 'languages' => []];

        $queryBuilder = $this->createQueryBuilder('entity');

        $result = $queryBuilder
            ->where($queryBuilder->expr()->eq('entity.status', $queryBuilder->expr()->literal('publish')))
            ->getQuery()->getResult();

        /**
         * @var Course $item
         */
        foreach ($result as $item) {
            $filtersData['categories'][$item->getCategory()->getId()] = $item->getCategory();
            $filtersData['users'][$item->getUser()->getId()] = $item->getUser();
            $filtersData['languages'][$item->getLanguage()] =  Intl::getLanguageBundle()->getLanguageName($item->getLanguage());
        }

        return $filtersData;
    }

    public function findSubscribedCourses($userId)
    {
        $queryBuilder = $this->createQueryBuilder('entity');

        $result = $queryBuilder
            ->leftJoin('AppBundle:CourseSubscriber', 'courseSubscriber', 'WITH', 'courseSubscriber.course = entity.id')
            ->where($queryBuilder->expr()->eq('courseSubscriber.user', $userId))
            ->getQuery()->getResult();

        return $result;
    }
}
