<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Lecture;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * LectureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LectureRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPreviousLecture(Lecture $lecture)
    {
        $rsm = new ResultSetMappingBuilder($this->getEntityManager());
        $rsm->addRootEntityFromClassMetadata('AppBundle\Entity\Lecture', 'lecture');

        $sql = 'select * from lecture where id = (select max(id) from lecture where id < ? and lecture.section_id = ?)';
        $query = $this->getEntityManager()->createNativeQuery($sql, $rsm);
        $query->setParameters([1 => $lecture->getId(), 2 => $lecture->getSection()->getId()]);

        $result = $query->getOneOrNullResult();

        return $result;
    }

    public function getNextLecture(Lecture $lecture)
    {
        $rsm = new ResultSetMappingBuilder($this->getEntityManager());
        $rsm->addRootEntityFromClassMetadata('AppBundle\Entity\Lecture', 'lecture');

        $sql = 'select * from lecture where id = (select min(id) from lecture where id > ? and lecture.section_id = ?)';
        $query = $this->getEntityManager()->createNativeQuery($sql, $rsm);
        $query->setParameters([1 => $lecture->getId(), 2 => $lecture->getSection()->getId()]);

        $result = $query->getOneOrNullResult();

        return $result;

    }
}
