<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Course;
use AppBundle\Entity\User;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByOwner(User $user)
    {
        $qb = $this->createQueryBuilder('entity');

        $result = $qb->innerJoin('entity.section', 'section')
            ->innerJoin('section.course', 'course')
            ->where($qb->expr()->eq('course.user', $user->getId()))
            ->getQuery()->getResult();


        return $result;
    }

    public function findByCourse(Course $course)
    {
        $qb = $this->createQueryBuilder('entity');

        $results = $qb->leftJoin('AppBundle:Section', 'section', 'WITH', 'entity.section = section.id')
            ->where($qb->expr()->eq('section.course', $course->getId()))->getQuery()->getResult();

        return $results;
    }

}
