api:
    resource: "@AppBundle/Controller/API"
    type: rest
    prefix:   /api

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app:
    resource: '@AppBundle/Controller/'
    type: annotation

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

google_login:
    path: /connect/check-google

resize:
    path: /files/{linkedEntityType}/{linkedEntityId}/{name}-{width}x{height}.{format}
    defaults: { _controller: AppBundle:File:resizeFileImage }
    methods: [GET]
